// Auto-generated by CRAFT Platform
// This file will be customized during deployment

import { resolveStellarNetworkConfig } from '@craft/stellar';

export const config = {
    branding: {
        appName: process.env.NEXT_PUBLIC_APP_NAME || 'Stellar DEX',
        primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '#4f9eff',
        secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || '#1a1f36',
    },
    stellar: resolveStellarNetworkConfig(process.env),
    features: {
        enableCharts: process.env.NEXT_PUBLIC_ENABLE_CHARTS === 'true',
        enableTransactionHistory: process.env.NEXT_PUBLIC_ENABLE_TRANSACTION_HISTORY === 'true',
        enableAnalytics: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS === 'true',
        enableNotifications: process.env.NEXT_PUBLIC_ENABLE_NOTIFICATIONS === 'true',
    },
} as const;

export default config;
