// Auto-generated by CRAFT Platform

import { resolveStellarNetworkConfig } from '@craft/stellar';

export const config = {
    branding: {
        appName: process.env.NEXT_PUBLIC_APP_NAME || 'Soroban DeFi',
        primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '#4f9eff',
        secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || '#1a1f36',
    },
    stellar: resolveStellarNetworkConfig(process.env),
    contracts: {
        // Contract addresses will be injected here by the CRAFT platform.
        // Expected shape (populated at deployment):
        // {
        //   liquidityPool?: string;     // Liquidity pool contract address
        //   yieldFarm?: string;         // Yield farming contract address
        //   tokenSwap?: string;         // Token swap contract address
        //   [key: string]: string | undefined;  // Additional contract addresses
        // }
    },
} as const;

export default config;
