/**
 * Fixture data for the deployment dashboard.
 * Replace with real API calls in production.
 */

import type { Deployment, DeploymentAnalytics } from '@/types/deployment';

export const MOCK_DEPLOYMENTS: Deployment[] = [
  {
    id: 'dep-001',
    name: 'stellar-dex-template',
    status: 'running',
    environment: 'production',
    trigger: 'push',
    commit: {
      sha: 'a3f9c12',
      message: 'feat: add liquidity pool calculation logic',
      author: 'jana.m',
      branch: 'main',
    },
    region: { id: 'us-east-1', label: 'US East', flag: '🇺🇸' },
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    url: 'https://stellar-dex.craft.app',
  },
  {
    id: 'dep-002',
    name: 'payment-gateway-v2',
    status: 'success',
    environment: 'production',
    trigger: 'push',
    commit: {
      sha: 'b7e2d45',
      message: 'fix: handle edge-case in invoice reconciliation',
      author: 'alex.t',
      branch: 'main',
    },
    region: { id: 'eu-west-1', label: 'EU West', flag: '🇪🇺' },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 2.8 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 127,
    url: 'https://payment-v2.craft.app',
    logsUrl: '#',
  },
  {
    id: 'dep-003',
    name: 'trading-bot-config',
    status: 'failed',
    environment: 'staging',
    trigger: 'push',
    commit: {
      sha: 'c1a8b90',
      message: 'chore: bump soroban-sdk to v21',
      author: 'morgan.k',
      branch: 'feat/sdk-upgrade',
    },
    region: { id: 'ap-southeast-1', label: 'AP Southeast', flag: '🌏' },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 4.9 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 43,
    logsUrl: '#',
  },
  {
    id: 'dep-004',
    name: 'nft-marketplace',
    status: 'queued',
    environment: 'preview',
    trigger: 'manual',
    commit: {
      sha: 'd4f5e78',
      message: 'feat: add auction countdown timer',
      author: 'priya.s',
      branch: 'feat/auction',
    },
    region: { id: 'us-west-2', label: 'US West', flag: '🇺🇸' },
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'dep-005',
    name: 'defi-yield-optimizer',
    status: 'success',
    environment: 'staging',
    trigger: 'schedule',
    commit: {
      sha: 'e9c3a56',
      message: 'perf: optimise compound interest loop',
      author: 'leo.r',
      branch: 'main',
    },
    region: { id: 'eu-central-1', label: 'EU Central', flag: '🇩🇪' },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 11.9 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 98,
    url: 'https://yield.staging.craft.app',
    logsUrl: '#',
  },
  {
    id: 'dep-006',
    name: 'cross-chain-bridge',
    status: 'rolling-back',
    environment: 'production',
    trigger: 'api',
    commit: {
      sha: 'f2b7d91',
      message: 'feat: add USDC corridor support',
      author: 'sam.w',
      branch: 'main',
    },
    region: { id: 'us-east-1', label: 'US East', flag: '🇺🇸' },
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    url: 'https://bridge.craft.app',
  },
  {
    id: 'dep-007',
    name: 'governance-dashboard',
    status: 'success',
    environment: 'production',
    trigger: 'push',
    commit: {
      sha: '3a1c882',
      message: 'ui: refresh proposal card design',
      author: 'nina.b',
      branch: 'main',
    },
    region: { id: 'us-east-1', label: 'US East', flag: '🇺🇸' },
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 23.8 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 211,
    url: 'https://gov.craft.app',
    logsUrl: '#',
  },
  {
    id: 'dep-008',
    name: 'staking-rewards-module',
    status: 'cancelled',
    environment: 'development',
    trigger: 'manual',
    commit: {
      sha: '8d4e550',
      message: 'wip: multi-token reward distribution',
      author: 'chen.x',
      branch: 'feat/multi-token',
    },
    region: { id: 'us-west-2', label: 'US West', flag: '🇺🇸' },
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 35.5 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 18,
  },
];

export const MOCK_ANALYTICS: DeploymentAnalytics = {
  totalDeployments: 248,
  successRate: 94.2,
  avgDurationSeconds: 118,
  activeDeployments: 2,
  failedLast24h: 1,
  deploymentsToday: 8,
  successRateTrend: +2.1,
  avgDurationTrend: -8,
};
